apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microservices-demo
resources:
  - frontend.yaml
  - auth-service.yaml
  - user-service.yaml
  - product-service.yaml
  - ingress.yaml
  - network-policy.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: k3s-microservices-demo
    includeSelectors: true
